version: '3.3'

services:
  dbserver:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: distribuidaclases
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "c:/db-distribuida:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    expose:
      - "5432"

  consul:
    image: consul:1.15.4
    command: |
      agent -dev
      -ui
      -bind 0.0.0.0
      -client 0.0.0.0
    ports:
      - "8500:8500"
    expose:
      - "8500"

  proxy:
    image: traefik:3.4.1
    command:
      - --api.insecure=true
      - --api.dashboard=true
      - --entrypoints.web.address=:80
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --providers.consulCatalog=true
      - --providers.consulCatalog.exposedByDefault=false
      - --providers.consulCatalog.endpoint.address=consul:8500
      - --providers.consulCatalog.refreshInterval=15s
    ports:
      - "80:80"
      - "8888:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - consul

  authors:
    image: jimmyortega/app-authors:latest
    environment:
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: postgres
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://dbserver:5432/distribuidaclases
      QUARKUS_HTTP_PORT: 8080
      CONSUL_HOST: consul
      CONSUL_PORT: "8500"
    ports:
      - "7070:8080"
    expose:
      - "8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.authors.rule=PathPrefix(`/authors`)"
      - "traefik.http.routers.authors.entrypoints=web"
      - "traefik.http.routers.authors.priority=5"
      - "traefik.http.services.authors.loadbalancer.server.port=8080"
    depends_on:
      - dbserver
      - consul

  books:
    image: jimmyortega/app-books:latest
    environment:
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: postgres
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://dbserver:5432/distribuidaclases
      QUARKUS_HTTP_PORT: 8080
      CONSUL_PORT: "8500"
    ports:
      - "9090:8080"
    expose:
      - "8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.books.rule=PathPrefix(`/books`)"
      - "traefik.http.routers.books.entrypoints=web"
      - "traefik.http.routers.books.priority=5"
      - "traefik.http.services.books.loadbalancer.server.port=8080"
    depends_on:
      - dbserver
      - consul

  customers:
    image: jimmyortega/app-customers:latest
    environment:
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: postgres
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://dbserver:5432/distribuidaclases
      QUARKUS_HTTP_PORT: 8080
      CONSUL_HOST: consul
      CONSUL_PORT: "8500"
    ports:
      - "7071:8080"
    expose:
      - "8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.customers.rule=PathPrefix(`/customers`)"
      - "traefik.http.routers.customers.entrypoints=web"
      - "traefik.http.routers.customers.priority=5"
      - "traefik.http.services.customers.loadbalancer.server.port=8080"
    depends_on:
      - dbserver
      - consul

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./configs:/etc/prometheus
    ports:
      - "9190:9090"
    expose:
      - "9090"

  grafana:
    image: grafana/grafana-oss:latest
    ports:
      - "3001:3000"
    expose:
      - "3000"
