global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'authors'
    metrics_path: /q/metrics
    static_configs:
      - targets: ['authors:8080']

  - job_name: 'books'
    metrics_path: /q/metrics
    static_configs:
      - targets: ['books:8080']

  - job_name: 'customers'
    metrics_path: /q/metrics
    static_configs:
      - targets: ['customers:8080']

  - job_name: 'prometheus'
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:9090']
